name:                HaskellThanLight
version:             0.1.0.0
github:              "https://github.com/Pomona-College-CS181-SP2020/HaskellThanLight"
license:             BSD3
author:              "Berkay Adanali, Joe Brennan, Gabe daMotta"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/HaskellThanLight#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src

executables:
  HaskellThanLight-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellThanLight

tests:
  HaskellThanLight-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - HaskellThanLight
